// <auto-generated />
using EncyklopediaZwierzat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EncyklopediaZwierzat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190603191820_DodanieOpini")]
    partial class DodanieOpini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EncyklopediaZwierzat.Models.Opinia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("NazwaUzytkownika");

                    b.Property<bool>("OczekujeOdpowiedzi");

                    b.Property<string>("Wiadomosc");

                    b.HasKey("Id");

                    b.ToTable("Opinie");
                });

            modelBuilder.Entity("EncyklopediaZwierzat.Models.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CZyJestGatunkiemChronionym");

                    b.Property<bool>("CzyZnajdeGoWPolsce");

                    b.Property<string>("KrajWystepowania");

                    b.Property<string>("MiniaturkaUrl");

                    b.Property<string>("Nazwa");

                    b.Property<string>("Odzywianie");

                    b.Property<string>("Opis");

                    b.Property<string>("Rasa");

                    b.Property<double>("SredniaDlugoscZycia");

                    b.Property<string>("Srodowisko");

                    b.Property<string>("ZdjecieUrl");

                    b.HasKey("Id");

                    b.ToTable("Zwierzeta");
                });
#pragma warning restore 612, 618
        }
    }
}
